# Generated by Django 4.2.3 on 2023-10-30 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
