# Generated by Django 4.2.3 on 2023-10-30 18:05

from django.db import migrations, models
import news.validators.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[news.validators.validators.validate_title],
            ),
        ),
    ]
